export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  GET_ALL_USER_REQUEST: "GET_ALL_USER_REQUEST",
  GET_ALL_USER_FAILURE: "GET_ALL_USER_FAILURE",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",

  GET_ALL_USER_DISABLED_REQUEST: "GET_ALL_USER_DISABLED_REQUEST",
  GET_ALL_USER_DISABLED_FAILURE: "GET_ALL_USER_DISABLED_FAILURE",
  GET_ALL_USER_DISABLED_SUCCESS: "GET_ALL_USER_DISABLED_SUCCESS",

  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",

  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_RESET: "DELETE_USER_RESET",

  UN_DELETE_USER_REQUEST: "UN_DELETE_USER_REQUEST",
  UN_DELETE_USER_FAILURE: "UN_DELETE_USER_FAILURE",
  UN_DELETE_USER_SUCCESS: "UN_DELETE_USER_SUCCESS",
  UN_DELETE_USER_RESET: "UN_DELETE_USER_RESET",
};

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",

  GET_ALL_CATE_DISABLE_REQUEST: "GET_ALL_CATE_DISABLE_REQUEST",
  GET_ALL_CATE_DISABLE_SUCCESS: "GET_ALL_CATE_DISABLE_SUCCESS",
  GET_ALL_CATE_DISABLE_FAILURE: "GET_ALL_CATE_DISABLE_FAILURE",

  GET_CATEGORY_BY_ID_REQUEST: "GET_CATEGORY_BY_ID_REQUEST",
  GET_CATEGORY_BY_ID_SUCCESS: "GET_CATEGORY_BY_ID_SUCCESS",
  GET_CATEGORY_BY_ID_FAILURE: "GET_CATEGORY_BY_ID_FAILURE",

  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  ADD_NEW_CATEGORY_RESET: "ADD_NEW_CATEGORY_RESET",

  UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",

  DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
  DELETE_CATEGORIES_RESET: "DELETE_CATEGORIES_RESET",

  ENABLE_CATEGORIES_REQUEST: "ENABLE_CATEGORIES_REQUEST",
  ENABLE_CATEGORIES_SUCCESS: "ENABLE_CATEGORIES_SUCCESS",
  ENABLE_CATEGORIES_FAILURE: "ENABLE_CATEGORIES_FAILURE",
};

export const productConstants = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  GET_ALL_PRODUCTS_DISABLE_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_DISABLE_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_DISABLE_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  GET_PRODUCT_BY_SLUG_REQUEST: "GET_PRODUCT_BY_SLUG_REQUEST",
  GET_PRODUCT_BY_SLUG_SUCCESS: "GET_PRODUCT_BY_SLUG_SUCCESS",
  GET_PRODUCT_BY_SLUG_FAILURE: "GET_PRODUCT_BY_SLUG_FAILURE",

  DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
  DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

  ENABLE_PRODUCT_REQUEST: "ENABLE_PRODUCT_REQUEST",
  ENABLE_PRODUCT_SUCCESS: "ENABLE_PRODUCT_SUCCESS",
  ENABLE_PRODUCT_FAILURE: "ENABLE_PRODUCT_FAILURE",

  DELETE_PRODUCT_BY_CATE_REQUEST: "DELETE_PRODUCT_BY_CATE_REQUEST",
  DELETE_PRODUCT_BY_CATE_SUCCESS: "DELETE_PRODUCT_BY_CATE_SUCCESS",
  DELETE_PRODUCT_BY_CATE_FAILURE: "DELETE_PRODUCT_BY_CATE_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ADD_PRODUCT_RESET: "ADD_PRODUCT_RESET",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
};

export const orderConstants = {
  GET_ALL_ORDERS_REQUEST: "GET_ALL_ORDERS_REQUEST",
  GET_ALL_ORDERS_SUCCESS: "GET_ALL_ORDERS_SUCCESS",
  GET_ALL_ORDERS_FAILURE: "GET_ALL_ORDERS_FAILURE",

  UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
  UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
  UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};

export const API_URL = "http://localhost:5000/api";
